# Welcome to the configuration file of BungeeBan.
# This configuration file contains the most important
# settings for the plugin. If you want to change the
# messages, edit messages.yml.
# Support: Skype: VinciPlayz Email: luca@vinciguerra.co
sql:
  driver: 'SQLITE'
  sqlite:
    filename: 'plugins/BungeeBan/bungeeban.db'
  mysql:
    hostname: '127.0.0.1'
    port: '3306'
    username: 'bb'
    password: '123abc'
    database: 'bb'
general:
  permissions:
    ban: 'lucavinci.bungeeban.ban'
    tempban: 'lucavinci.bungeeban.tempban'
    unban: 'lucavinci.bungeeban.unban'
    ban-broadcast: 'lucavinci.bungeeban.banbroadcast'
    mute: 'lucavinci.bungeeban.mute'
    tempmute: 'lucavinci.bungeeban.tempmute'
    unmute: 'lucavinci.bungeeban.unmute'
    mute-broadcast: 'lucavinci.bungeeban.mutebroadcast'
    kick: 'lucavinci.bungeeban.kick'
    kick-broadcast: 'lucavinci.bungeeban.kickbroadcast'
    check: 'lucavinci.bungeeban.check'